openapi: 3.0.3
info:
  title: Keycloak VC issuer plugin
  description: API spec for the Keycloak issuer plugin
  version: 0.0.1
externalDocs:
  description: API Documentation
  url: https://openid.net/specs/openid-4-verifiable-credential-issuance-1_0.html
tags:
  - name: Public
    description: Public Endpoints
  - name: CSS
    description: CSS Endpoints
  - name: Img
    description: Img Endpoints
  - name: Font
    description: Font Endpoints
paths:
  /realms/EAAProvider:
    get:
      tags:
        - Public
      summary: Get EAAProvider Realm
      description: Retrieves the EAAProvider Realm from a specific URL.
      responses:
        '200':
          description: Successful response
  /resources/nsyq5/common/keycloak/node_modules/patternfly/dist/fonts/OpenSans-Bold-webfont.woff2:
    get:
      tags:
        - Public
        - Font
      summary: Get Font File
      description: Retrieve the OpenSans-Bold-webfont.woff2 font file from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'application/font-woff2':
              schema:
                type: string  # Assuming binary data (base64-encoded)
                format: binary
  /resources/nsyq5/login/keycloak/img/favicon.ico:
    get:
      tags:
        - Public
        - Img
      summary: Get Favicon
      description: Retrieve the favicon.ico image from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'image/x-icon':
              schema:
                type: string  # Assuming binary data (base64-encoded)
                format: binary
  /resources/nsyq5/common/keycloak/node_modules/patternfly/dist/fonts/OpenSans-Light-webfont.woff2:
    get:
      tags:
        - Public
        - Font
      summary: Get Font File
      description: Retrieve the OpenSans-Light-webfont.woff2 font file from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'application/font-woff2':
              schema:
                type: string  # Assuming binary data (base64-encoded)
                format: binary
  /resources/nsyq5/common/keycloak/node_modules/patternfly/dist/fonts/OpenSans-Regular-webfont.woff2:
    get:
      tags:
        - Public
        - Font
      summary: Get Font File
      description: Retrieve the OpenSans-Regular-webfont.woff2 font file from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'application/font-woff2':
              schema:
                type: string  # Assuming binary data (base64-encoded)
                format: binary
  /resources/nsyq5/login/keycloak/img/keycloak-bg.png:
    get:
      tags:
        - Public
        - Img
      summary: Get Image
      description: Retrieve the keycloak-bg.png image from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'image/png':
              schema:
                type: string  # Assuming binary data (base64-encoded)
                format: binary
  /resources/nsyq5/login/keycloak/css/login.css:
    get:
      tags:
        - Public
        - CSS
      summary: Get CSS file
      description: Retrieve the login.css file from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'text/css':
              schema:
                type: string
  /resources/nsyq5/common/keycloak/lib/pficon/pficon.css:
    get:
      tags:
        - Public
        - CSS
      summary: Get CSS file
      description: Retrieve the pficon.css file from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'text/css':
              schema:
                type: string
  /resources/nsyq5/common/keycloak/node_modules/patternfly/dist/css/patternfly-additions.min.css:
    get:
      tags:
        - Public
        - CSS
      summary: Get CSS file
      description: Retrieve the patternfly-additions.min.css file from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'text/css':
              schema:
                type: string
  /resources/nsyq5/common/keycloak/node_modules/patternfly/dist/css/patternfly.min.css:
    get:
      tags:
        - Public
        - CSS
      summary: Get CSS file
      description: Retrieve the patternfly.min.css file from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'text/css':
              schema:
                type: string
  /resources/nsyq5/common/keycloak/web_modules/@patternfly/react-core/dist/styles/app.css:
    get:
      tags:
        - Public
        - CSS
      summary: Get CSS file
      description: Retrieve the app.css file from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'text/css':
              schema:
                type: string
  /resources/nsyq5/common/keycloak/web_modules/@patternfly/react-core/dist/styles/base.css:
    get:
      tags:
        - Public
        - CSS
      summary: Get CSS file
      description: Retrieve the base.css file from the specified endpoint.
      responses:
        '200':
          description: Successful response
          content:
            'text/css':
              schema:
                type: string
  /realms/EAAProvider/broker/gicar/endpoint:
    post:
      tags:
        - Public
      summary: Description of the endpoint
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                RelayState:
                  type: string
                SAMLResponse:
                  type: string
      responses:
        '200':
          description: Successful response
  /realms/EAAProvider/broker/gicar/login:
    get:
      tags:
        - Public
      summary: GICAR Login
      parameters:
        - name: session_code
          in: query
          required: true
          schema:
            type: string
          example: nltTOaaxTNFq3u642NPDBlSBxqscRrorIg0mkX6thuM
        - name: client_id
          in: query
          required: true
          schema:
            type: string
          example: oidc4vci-wallet-client
        - name: tab_id
          in: query
          required: true
          schema:
            type: string
          example: SDgCS1bH4pU
      responses:
        '200':
          description: Successful response
  /realms/EAAProvider/protocol/openid-connect/auth:
    get:
      tags:
        - Public
      summary: OIDC Authentication
      parameters:
        - name: client_id
          in: query
          required: true
          schema:
            type: string
          example: oidc4vci-wallet-client
        - name: redirect_uri
          in: query
          required: true
          schema:
            type: string
          example: https://example/callback
        - name: response_type
          in: query
          required: true
          schema:
            type: string
          example: code
        - name: scope
          in: query
          required: true
          schema:
            type: string
          example: openid gicar_id_token
        - name: nonce
          in: query
          required: true
          schema:
            type: string
          example: ba464f1a81dcbd46a4e5dd7cec7fc5e77c8nvyU8D
        - name: state
          in: query
          required: true
          schema:
            type: string
          example: 33c5856ce4c973d65de165270bafaf4df2fw3nXh1
        - name: code_challenge
          in: query
          required: true
          schema:
            type: string
          example: k54-68f_grslUymjC3bvMTtfHNJcLFJZDP1dU-NMpj0
        - name: code_challenge_method
          in: query
          required: true
          schema:
            type: string
          example: S256
        - name: kc_idp_hint
          in: query
          required: true
          schema:
            type: string
          example: gicar
      responses:
        '200':
          description: Successful response
  /realms/EAAProvider/.well-known/openid-configuration:
    get:
      tags:
        - Public
      operationId: getOpenIdConfig
      summary: provide SIOP-2 metadata
      responses:
        '200':
          description: OpenID Provider Metadata
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SIOPMetadata'
  /realms/EAAProvider/protocol/openid-connect/token:
    post:
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                client_id:
                  type: string
                username:
                  type: string
                password:
                  type: string
                client_secret:
                  type: string
                grant_type:
                  type: string
      tags:
        - Public
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                access_token: <your_access_token>
                token_type: Bearer
                expires_in: 3600
                refresh_token: <your_refresh_token>
                refresh_expires_in: 1800
                not-before-policy: 0
                session_state: 721cc9cc-66de-83fc-a0f8-24e13al2a9e1
                scope: profile email
  /realms/EAAProvider/protocol/openid-connect/certs:
    get:
      summary: Get OpenID Connect Certificates
      tags:
        - Public
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                keys:
                  - kty: RSA
                    kid: <your_key_id>
                    use: sig
                    n: <your_modulus>
                    e: <your_exponent>
                    x5c:
                      - <your_x509_certificate>
                    x5t: <your_x509_thumbprint>
                    x5t#S256: <your_x509_sha256_thumbprint>
  /realms/EAAProvider/protocol/openid-connect/userinfo:
    get:
      summary: Get User Information
      tags:
        - Public
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              example:
                sub: <user_subject>
                preferred_username: <preferred_username>
                email: <user_email>
      security:
        - BearerAuth: [read]
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
  parameters:
    IssuerDid:
      description: Did configured for the requested issuer
      name: issuerDid
      in: path
      required: true
      schema:
        type: string
        example: did:key:z6MkqmaCT2JqdUtLeKah7tEVfNXtDXtQyj4yxEgV11Y5CqUa
  schemas:
    SignatureAlgorithm:
      type: string
      enum: [ "RS256","ES256","ES256K","EdDSA" ]
    SIOPMetadata:
      type: object
      properties:
        authorization_endpoint:
          description: URL of the Self-Issued OP used by the RP to perform Authentication of the End-User. Can be custom URI scheme, or Universal Links/App links.
          type: string
          format: url
          example: "https://my-keycloak.org"
        issuer:
          description: URL using the https scheme with no query or fragment component that the Self-Issued OP asserts as its Issuer Identifier. MUST be identical to the iss Claim value in ID Tokens issued from this Self-Issued OP.
          type: string
          format: url
          example: "https://kc-one.batterypass.fiware.dev/realms/fiware-server/verifiable-credential"
        response_types_supported:
          type: array
          description: A JSON array of strings representing supported response types. MUST be id_token.
          items:
            type: string
            enum: [ "id_token" ]
        scopes_supported:
          description: A JSON array of strings representing supported scopes. MUST support the openid scope value
          type: array
          items:
            type: string
            enum: [ "openid" ]
        subject_types_supported:
          description: A JSON array of strings representing supported subject types. Valid values include pairwise and public
          type: array
          items:
            type: string
            enum: [ "pairwise", "public" ]
        id_token_signing_alg_values_supported:
          description: A JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP for the ID Token to encode the Claims in a JWT [RFC7519]. Valid values include RS256, ES256, ES256K, and EdDSA.
          type: array
          items:
            $ref: '#/components/schemas/SignatureAlgorithm'
          example:
            - "EdDSA"
            - "ES256"
        request_object_signing_alg_values_supported:
          description: A JSON array containing a list of the JWS signing algorithms (alg values) supported by the OP for Request Objects, which are described in Section 6.1 of [OpenID.Core]. Valid values include none, RS256, ES256, ES256K, and EdDSA
          type: array
          items:
            $ref: '#/components/schemas/SignatureAlgorithm'
        subject_syntax_types_supported:
          type: array
          items:
            type: string
            enum:
              - "urn:ietf:params:oauth:jwk-thumbprint"
              - "did:key"
          example:
            - "did:key"
      required:
        - authorization_endpoint
        - issuer
        - response_types_supported
        - scopes_supported
        - subject_types_supported
        - id_token_signing_alg_values_supported
        - request_object_signing_alg_values_supported